export { default as AboutUs } from "./AboutUs";
export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Login } from "./Login";
// export { default as NewGeneralPost } from "../components/composeComponents/NewGeneralPost";
// export { default as NewInterviewPost } from "../components/composeComponents/NewInterviewPost";
// export { default as NewLearnPost } from "./NewLearnPost";
// export { default as NewProjectPost } from "./NewProjectPost";
export { default as Register } from "./Register";
export { default as MyAccount } from "./MyAccount";
export { default as PersonalInfo } from "./PersonalInfo";
export { default as Post } from "./Post";
export { default as PostList } from "./postList/PostList";
