export { default as AboutUs } from "./AboutUs";
export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as MyAccount } from "./myAccount/MyAccount";
export { default as PersonalInfo } from "./myAccount/PersonalInfo";
export { default as Post } from "./Post";
export { default as PostList } from "./postList/PostList";
